---
title: "optimadmm"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, results='hide'}
if(!require(Deriv)){install.packages("Deriv")};library(Deriv)
if(!require(evd)){install.packages("evd")};library(evd)

# optim control
optim_controlList = list()
optim_controlList$maxit = 1e+3
```

#### function
```{r}
#z_function
func_z <- function(dmatrix,mu,u,lam,rho)
{
  z = ifelse(abs(dmatrix %*% mu + u) > (lam/rho) ,
             (dmatrix %*% mu) + u - sign(u + (dmatrix %*% mu)) * (lam /rho), 0)
  return(z)
}
#u_function
func_u <- function(dmatrix,mu,z,u) 
{
  u <- u + (dmatrix %*% mu) - z
  return(u)
}
#dmatrix
mat_func = function(n) {
  m = matrix(0,n-2,n)   
  for (i in 1:(n-2)) {
    m[i,i] = 1
    m[i,i+1] = -2
    m[i,i+2] = 1
  }
  return(m)
}
```

#### gevfunction 
```{r,results='hide'}
gevreg = function(x, z)
{
  
  l2gev = function (tvec, dmatrix, rho, z_init, u_init)
  {
 
    loc.vec = tvec[1:n]
    # loglikelihood
    v1 = - sum(lgev(x, loc = loc.vec, scale = tvec[n+1], shape = tvec[n+2]))
    
    # lagrangian term
    v2 = (rho/2)*sum(((dmatrix %*% loc.vec) - z_init + u_init)^2)
    v = v1 + v2
    return(v)
  }
  
  lgev = function (x, loc = 0, scale = 1, shape = 0) 
  {
    if (min(scale) <= 0) 
      return( - 1e+6)
    if (length(shape) != 1) 
      stop("invalid shape")
    x <- (x - loc)/scale
    if (shape == 0) 
      d <- log(1/scale) - x - exp(-x)
    else {
      nn <- length(x)
      xx <- 1 + shape * x
      xxpos <- xx[xx > 0 | is.na(xx)]
      scale <- rep(scale, length.out = nn)[xx > 0 | is.na(xx)]
      d <- numeric(nn)
      d[xx > 0 | is.na(xx)] <- log(1/scale) - xxpos^(-1/shape) - 
        (1/shape + 1) * log(xxpos)
      d[xx <= 0 & !is.na(xx)] <- -(1e+6)
    }
    return(d)
  }
  
  return( optim(tvec, l2gev, dmatrix = dmatrix,
                rho=rho, z_init = z_init, u_init = u_init, method = "BFGS")$par )
}
```
  

#### value  
 * $\mu = z\beta$
```{r}
#set value
n = 100
true_theta=c(30,0.1)
true_beta = rep(0,n)

y = sin(seq(0,2*pi,length = n))*10; mt = y +100  
x= rep(0,n); set.seed(1)
for (i in 1:n) {
  x[i] = rgev(1,loc =mt[i],scale=true_theta[1],shape=true_theta[2])
}
z = diag(n)

# init value
dmatrix = mat_func(n)
rho = 0.5;lam = 100
z_init = rep(0,n-2) ; u_init = rep(1,n-2)

start <- list()
start$scale <- sqrt(6 * var(x))/pi
start$loc <- mean(x) - 0.58 * start$scale 
tvec = c(true_beta,0,0)
tvec[1:n] = start$loc  
tvec[n+1] = start$scale 
```

#### update
```{r}
#update
for (iter in 1:500) {
  # cat("*****iter:::", iter, "\n")
  
  #mu, sigma, k optim
  old_tvec = gevreg(x = x,z = z)
  old_mu = old_tvec[1:n]
  
    # z update in ADMM
  tmp_z = func_z(dmatrix = dmatrix, mu = old_mu, u = u_init,lam = lam, rho = rho)
  
  # u update in ADMM
  tmp_u = func_u(dmatrix = dmatrix , mu = old_mu, z = tmp_z, u = u_init)
  
  u_init = tmp_u ; z_init = tmp_z
  tvec = old_tvec
}

plot(old_mu, type = "l",main = "optim")
points(x,col="red")
```

